[package]
name = "retry"
version = "0.1.0"
authors = ["Michel Perez <michel.ingesoft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
actix-rt = "0.2.4"
actix-http = "0.2.9"
actix-web = "1.0.3"
awc = "0.2.4"
futures = "0.1"
serde = "1.0.94"
failure = "0.1.5"
